- app.py
Depends-On: https://github.com/thoth-station/storages/issues/98
> Store information about CVEs

- app.py
This addresses mainly exception that is raised by solver if the given package
was not found on index (it was deleted).
> Skip package if there was an error in resolution

- app.py
> Normalize Python package names

- .coafile
- .zuul.yaml
- openshift/cronJob-template.yaml
Signed-off-by: Christoph Görn <goern@redhat.com>
> added image stream tag and namespace parameter

- openshift/buildConfig-template.yaml
- openshift/cronJob-template.yaml
- openshift/imageStream-template.yaml
Required the fix for deployment in the new cluster.
> minor fix template for openshift >=3.11

- app.py
Fixes: https://github.com/thoth-station/cve-update-job/issues/195
> Report warning instead of error when a package is not found

- app.py
Depends-On: https://github.com/thoth-station/storages/pull/1366
> Update CVE record

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/major-release.md
- .github/ISSUE_TEMPLATE/minor-release.md
- .github/ISSUE_TEMPLATE/patch-release.md
- .thoth.yaml
include github issue templates
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
> include github issue templates

- app.py
It returns a list of versions matched (sorted).
Fixes: #354
> Solver does not take all_versions parameter anymore

- app.py
> Added version file

- Pipfile
- Pipfile.lock
- app.py
Depends-On: https://github.com/thoth-station/messaging/pull/306
Related-To: https://github.com/thoth-station/cve-update-job/issues/373
> make cve-update-job kafka producer

- .aicoe-ci.yaml
Fixes: #395 
update aicoe-ci configuration for cve-update-job
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
> update aicoe-ci configuration for cve-update-job

- Pipfile
- Pipfile.lock
- app.py
Fixes: https://github.com/thoth-station/cve-update-job/issues/404
Related: https://github.com/thoth-station/cve-update-job/issues/404
Fixes: https://github.com/thoth-station/core/issues/266
> Start using pypa/advisory-db as a source of CVEs

- app.py
Related: https://github.com/thoth-station/adviser/issues/2142
Requires: https://github.com/thoth-station/storages/pull/2460
> Set CVE timestamp after each sucessful CVE update

- app.py
Related: https://github.com/thoth-station/adviser/issues/2149
Requires: https://github.com/thoth-station/storages/pull/2461/
Related: https://github.com/thoth-station/adviser/pull/2151
> Provide a link to the reported CVE vulnerability

- README.rst
point the tags badges to github tags
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
> point the tags badges to github tags

- .pre-commit-config.yaml
- app.py
should resolve the ci failures in #470
> Fix pre-commits checks failings

- .prow.yaml
Using mypy from precommit
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>
> Using mypy from precommit

- Pipfile
- Pipfile.lock
- Add mypy to dev dependencies
> Add mypy in dev deps

- app.py
> Tidying up exception logging
